global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'icn-mcp-server'
    static_configs:
      - targets: ['mcp-server:8787']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: 'http'