name: CI
on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
      npm_config_build_from_source: "false"
      GITHUB_OWNER: InterCooperative-Network
      GITHUB_REPO: icn-mcp
      GITHUB_DEFAULT_BRANCH: main
      GITHUB_WEBHOOK_SECRET: testsecret
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - run: npm ci

      - run: npm run lint

      - run: mkdir -p var

      - run: npm run migrate:ci --if-present

      - name: Validate OpenAPI spec
        run: |
          npx @redocly/cli lint docs/api/openapi.yaml --skip-rule=no-unused-components

      - run: npm test -ws --if-present

      - run: npm run build

